version: "2.1"
orbs:
  docker: circleci/docker@0.5.13

workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          before_build:
            - run:
                name: set image tag 
                command: |
                  if [[ -v CIRCLE_TAG ]]; then
                    echo 'export IMAGE_TAG=$(echo $CIRCLE_TAG | tr -d v)' >> $BASH_ENV
                  else
                    echo 'export IMAGE_TAG=$CIRCLE_BRANCH' >> $BASH_ENV
                  fi
          lint-dockerfile: true
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: $IMAGE_TAG
          registry: $DOCKER_REGISTRY
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - master
