'use strict';

module.exports = {
    FX_QUOTE_A_RECEIVED: 'FX_QUOTE_A_RECEIVED',
    FX_QUOTE_B_CREATED: 'FX_QUOTE_B_CREATED',
    FX_QUOTE_B_SENT: 'FX_QUOTE_B_SENT',
    FX_QUOTE_B_RESPONSE_RECEIVED: 'FX_QUOTE_B_RESPONSE_RECEIVED',
    FX_QUOTE_A_RESPONSE_CREATED: 'FX_QUOTE_A_RESPONSE_CREATED',
    FX_QUOTE_A_RESPONSE_SENT: 'FX_QUOTE_A_RESPONSE_SENT',
    FX_TRANSFER_A_RECEIVED: 'FX_TRANSFER_A_RECEIVED',
    FX_TRANSFER_B_CREATED: 'FX_TRANSFER_B_CREATED',
    FX_TRANSFER_B_SENT: 'FX_TRANSFER_B_SENT',
    FX_TRANSFER_B_FULFILMENT_RECEIVED: 'FX_TRANSFER_B_FULFILMENT_RECEIVED',
    FX_TRANSFER_B_PAYEE_TRANSFER_COMMITTED: 'FX_TRANSFER_B_PAYEE_TRANSFER_COMMITTED',
    FX_TRANSFER_B_PAYEE_TRANSFER_COMMITTED_ACK: 'FX_TRANSFER_B_PAYEE_TRANSFER_COMMITTED_ACK',
    FX_TRANSFER_A_FULFILMENT_CREATED: 'FX_TRANSFER_A_FULFILMENT_CREATED',
    FX_TRANSFER_A_FULFILMENT_SENT: 'FX_TRANSFER_A_FULFILMENT_SENT',
    FX_TRANSFER_A_PAYER_TRANSFER_COMMITTED: 'FX_TRANSFER_A_PAYER_TRANSFER_COMMITTED',
    FX_TRANSFER_A_PAYER_TRANSFER_COMMITTED_ACK: 'FX_TRANSFER_A_PAYER_TRANSFER_COMMITTED_ACK',
};